version: '3'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./certbot_data:/etc/letsencrypt
    env_file: .env
